src/AppBundle/Entity/Benefit.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 *
 * @ORM\Table(name="benefit")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\BenefitRepository")
 */
class Benefit
{
    const TYPE = array(1=>'Beca', 2=>'Contrato');
    const TYPE_OPTIONS = array('Beca'=>1, 'Contrato'=>2);
	/**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
	private $id;

	/**
     * @ORM\Column(name="type", type="integer", nullable=true)
     * @Assert\NotNull(groups={"benefit"})
     * @Assert\Choice(choices = {1, 2}, groups={"benefit"})
     */
	private $type;

	/**
     * @var Area
     *
     * @ORM\ManyToOne(targetEntity="Area")
     */
	private $area;

	/**
     * @var Secretariat
     *
     * @ORM\ManyToOne(targetEntity="Secretariat")
     */
	private $secretariat;

    /**
     * @var Direction
     *
     * @ORM\ManyToOne(targetEntity="Direction")
     */
    private $direction;

	/**
     * @var Ministry
     *
     * @ORM\ManyToOne(targetEntity="Ministry")
     */
	private $ministry;

	/**
    * @ORM\Column(name="area_manager", type="string", length=200, nullable=true)
    * @Assert\Length(max=200, groups={"benefit_user"})
    */
	private $areaManager;

    /**
    * @ORM\Column(name="institution_other", type="string", length=200, nullable=true)
    * @Assert\Length(max=200, groups={"benefit_user"})
    */
    private $institutionOther;


    /**
    * @ORM\OneToMany(targetEntity="FilePdf", mappedBy="benefit",cascade={"all"})
    */
	private $filePdfs;

    private $pdfs;

    /**
    * @ORM\ManyToOne(targetEntity="User")
    */
    private $user;

    public function __construct()
    {
        $this->setNationality('Argentina');
        $this->setZipCode('5300');
        $this->filePdfs = new ArrayCollection();
        $this->pdfs = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeName()
    {
        return ($this->getType()) ? self::TYPE[$this->getType()] : '';
    }

    public function getBloodTypeName()
    {
        return ($this->getBloodType()) ? self::BLOOD_TYPE[$this->getBloodType()] : '';
    }

    public function getCivilStatusName()
    {
        return self::CIVIL_STATUS[$this->getCivilStatus()];
    }

    /**
     * @return mixed
     */
    public function getArea()
    {
        return $this->area;
    }

    /**
     * @param mixed $area
     *
     * @return self
     */
    public function setArea(Area $area = null)
    {
        $this->area = $area;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSecretariat()
    {
        return $this->secretariat;
    }

    /**
     * @param mixed $secretariat
     *
     * @return self
     */
    public function setSecretariat(Secretariat $secretariat = null)
    {
        $this->secretariat = $secretariat;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMinistry()
    {
        return $this->ministry;
    }

    /**
     * @param mixed $ministry
     *
     * @return self
     */
    public function setMinistry(Ministry $ministry = null)
    {
        $this->ministry = $ministry;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAreaManager()
    {
        return $this->areaManager;
    }

    /**
     * @param mixed $areaManager
     *
     * @return self
     */
    public function setAreaManager($areaManager)
    {
        $this->areaManager = $areaManager;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFilePdfs()
    {
        return $this->filePdfs;
    }

    /**
     * @param mixed $files
     *
     * @return self
     */
    public function setFilePdfs($files)
    {
        $this->filePdfs = $filePdfs;

        return $this;
    }

    public function addFilePdf(FilePdf $file)
    {
        $this->filePdfs->add($file);
        $file->setBenefit($this);
    }

    public function removeFilePdf(FilePdf $file)
    {
        $this->filePdfs->removeElement($file);
        $file->setBenefit(null);
    }

    const BLOOD_TYPE = array(0=>'',1=>'0-',2 => '0+',3=>'A-',4=>'A+',5=>'B-',6=>'B+',7=>'AB-',8=>'AB+');
    const BLOOD_TYPE_OPTIONS = array(''=>0,'0-'=>1,'0+'=>2,'A-'=>3,'A+'=>4,'B-'=>5,'B+'=>6,'AB-'=>7,'AB+'=>8);
    const CIVIL_STATUS = array(0=>'Soltero',1=>'Casado',2=>'Viudo',3=>'Divorsiado');
    const CIVIL_STATUS_OPTIONS = array('Soltero'=>0,'Casado'=>1,'Viudo'=>2,'Divorsiado'=>3);

    /************************************************************************
    *
    * Basic data
    *
    *************************************************************************/

    /**
    * @ORM\Column(name="name", type="string", length=200, nullable=true)
    * @Assert\NotBlank(groups={"benefit_user"})
    * @Assert\Length(max=200, groups={"benefit_user"})
    */
    private $name;

    /**
    * @ORM\Column(name="lastname", type="string", length=200, nullable=true)
    * @Assert\NotBlank(groups={"benefit_user"})
    * @Assert\Length(max=200, groups={"benefit_user"})
    */
    private $lastname;

    /**
    * @ORM\Column(name="dni", type="string", length=10, nullable=true)
    * @Assert\Length(max=8, groups={"benefit_user"})
    */
    private $dni;

    /**
    * @ORM\Column(name="passport", type="string", length=10, nullable=true)
    * @Assert\Length(max=9, groups={"benefit_user"})
    */
    private $passport;

    /**
    * @ORM\Column(name="cuil", type="string", length=15, nullable=true)
    * @Assert\NotBlank(groups={"benefit_user"})
    * @Assert\Length(max=13, groups={"benefit_user"})
    */
    private $cuil;

    /**
    * @ORM\Column(name="birthday", type="date", nullable=true)
    * @Assert\Date(groups={"benefit_user"})
    */
    private $birthday;

    /**
    * @ORM\Column(name="place", type="string", length=255, nullable=true)
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $place;

    /**
    * @ORM\Column(name="nationality", type="string", length=255, nullable=true)
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $nationality;

    /**
    * @ORM\Column(name="blood_type", type="integer", nullable=true)
    * @Assert\NotBlank(groups={"benefit_user"})
    * @Assert\Choice(choices = {0, 1, 2, 3, 4, 5}, groups={"benefit_user"})
    */
    private $bloodType;

    /**
    * @ORM\Column(name="civil_status", type="integer", nullable=true)
    * @Assert\NotBlank(groups={"benefit_user"})
    * @Assert\Choice(choices = {0, 1, 2, 3, 4, 5}, groups={"benefit_user"})
    */
    private $civilStatus;

    /**
    * @ORM\Column(name="phone", type="string", length=255, nullable=true)
    * @Assert\NotBlank(groups={"benefit_user"})
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $phone;

    /**
    * @ORM\Column(name="email", type="string", length=255, nullable=true)
    * @Assert\Email(groups={"benefit_user"})
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $email;

    /************************************************************************
    *
    * Address data
    *
    *************************************************************************/

    /**
    * @ORM\Column(name="street", type="string", length=255, nullable=true)
    * @Assert\Email(groups={"benefit_user"})
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $street;

    /**
    * @ORM\Column(name="neighborhood", type="string", length=255, nullable=true)
    * @Assert\Email(groups={"benefit_user"})
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $neighborhood;

    /**
    * @ORM\Column(name="city", type="string", length=255, nullable=true)
    * @Assert\Email(groups={"benefit_user"})
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $city;

    /**
    * @ORM\Column(name="depto", type="string", length=255, nullable=true)
    * @Assert\Email(groups={"benefit_user"})
    * @Assert\Length(max=255, groups={"benefit_user"})
    */
    private $depto;

    /**
    * @ORM\Column(name="zipCode", type="integer", length=4, nullable=true)
    * @Assert\Email(groups={"benefit_user"})
    * @Assert\Length(max=4, groups={"benefit_user"})
    */
    private $zipCode;

    /************************************************************************
    *
    * Study data
    *
    *************************************************************************/

    /**
    * @ORM\Column(name="is_primary_school", type="boolean", nullable=true)
    */
    private $isPrimarySchool;

    /**
    * @ORM\Column(name="is_basic_cycle", type="boolean", nullable=true)
    */
    private $isBasicCycle;

    /**
    * @ORM\Column(name="is_high_school", type="boolean", nullable=true)
    */
    private $isHighSchool;

    /**
    * @ORM\Column(name="is_tertiary_school", type="boolean", nullable=true)
    */
    private $isTertiarySchool;

    /**
    * @ORM\Column(name="is_universitary_degree", type="boolean", nullable=true)
    */
    private $isUniversitaryDegree;

    /**
    * @ORM\Column(name="is_postgrade", type="boolean", nullable=true)
    */
    private $isPostgrade;

    /**
    * @ORM\Column(name="degree", type="string", length=255, nullable=true)

src/AppBundle/Form/BenefitType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Benefit;
use AppBundle\Form\FilePdfType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BenefitType extends AbstractType
{
	
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('type',ChoiceType::class,array(
				'choices' => Benefit::TYPE_OPTIONS,
				'label' => 'Tipo de beneficio'
			))
			->add('area',EntityType::class,array(
				'class' => 'AppBundle:Area',
				'choice_label' => 'name',
				'choice_value' => 'id',
				'label' => 'Área / Coordinación / Unidad',
				'placeholder' => 'Seleccionar'
			))
			->add('secretariat',EntityType::class,array(
				'class' => 'AppBundle:Secretariat',
				'choice_label' => 'name',
				'choice_value' => 'id',
				'label' => 'Subsecretaría',
				'placeholder' => 'Seleccionar'
			))
			->add('direction',EntityType::class,array(
				'class' => 'AppBundle:Direction',
				'choice_label' => 'name',
				'choice_value' => 'id',
				'label' => 'Dirección',
				'placeholder' => 'Seleccionar'
			))
			->add('ministry',EntityType::class,array(
				'class' => 'AppBundle:Ministry',
				'choice_label' => 'name',
				'choice_value' => 'id',
				'label' => 'Ministerio / Secretaria',
				'placeholder' => 'Seleccionar'
			))
			->add('areaManager',TextType::class,array(
				'label' => 'Encargado del área'
			))
			->add('name',TextType::class,array(
				'label' => 'Nombres'
			))
			->add('lastname',TextType::class,array(
				'label' => 'Apellidos'
			))
			->add('dni',TextType::class,array(
				'label' => 'DNI'
			))
			->add('passport',TextType::class,array(
				'label' => 'Pasaporte',
				'required' => false
			))
			->add('cuil',TextType::class,array(
				'label' => 'Cuil',
				'attr' => array('class'=>'cuil')
			))
			->add('birthday',DateType::class,array(
				'widget' => 'single_text',
				'format' => 'dd-MM-yyyy',
				'label' => 'Nacimiento'
			))
			->add('place',TextType::class,array(
				'label' => 'Lugar de nacimiento'
			))
			->add('city',TextType::class,array(
				'label' => 'Localidad'
			))
			->add('nationality',TextType::class,array(
				'label' => 'Nacionalidad'
			))
			->add('bloodType',ChoiceType::class,array(
				'choices' => Benefit::BLOOD_TYPE_OPTIONS,
				'label' => 'Grupo sanguíneo'
			))
			->add('civilStatus',ChoiceType::class,array(
				'choices' => Benefit::CIVIL_STATUS_OPTIONS,
				'label' => 'Estado civil'
			))
			->add('phone',TextType::class,array(
				'label' => 'Teléfono'
			))
			->add('email',EmailType::class,array(
				'label' => 'Email',
				'required' => false
			))
			->add('street',TextType::class,array(
				'label' => 'Calle'
			))
			->add('neighborhood',TextType::class,array(
				'label' => 'Barrio'
			))
			->add('depto',TextType::class,array(
				'label' => 'Departamento'
			))
			->add('zipCode',TextType::class,array(
				'label' => 'Código postal'
			))
			->add('isPrimarySchool',CheckboxType::class,array(
				'label' => '¿Primaria completo?',
				'required' => false
			))
			->add('isBasicCycle',CheckboxType::class,array(
				'label' => '¿Ciclo básico?',
				'required' => false	
			))
			->add('isHighSchool',CheckboxType::class,array(
				'label' => '¿Secundaria completo?',
				'required' => false
			))
			->add('isTertiarySchool',CheckboxType::class,array(
				'label' => '¿Terciario completo?',
				'required' => false
			))
			->add('isUniversitaryDegree',CheckboxType::class,array(
				'label' => '¿Título universitario?',
				'required' => false
			))
			->add('isPostgrade',CheckboxType::class,array(
				'label' => '¿Posgrado?',
				'required' => false
			))
			->add('degree',TextType::class,array(
				'label' => 'Título obtenido',
				'required' => false
			))
			->add('actualStudy',TextType::class,array(
				'label' => 'Estudios en curso',
				'required' => false
			))
			->add('institutionOther',TextType::class,array(
				'label' => 'Institución / otros',
				'required' => false
			))
			->add('pdfs', FileType::class,array(
				'multiple' => true
			))
			->add('user',EntityType::class,array(
				'class' => 'AppBundle:User',
				//'choice_label' => 'name',
				'choice_value' => 'id',
				'label' => 'Usuario',
				'placeholder' => 'Seleccionar'
			))
		;
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => 'AppBundle\Entity\Benefit',
			'validation_groups' => 'benefit'
		));
	}

	public function getBlockPrefix()
	{
		return 'benefit';
	}

	public function getName() 
	{
        return 'benefit';
    }
}

?>

src/AppBundle/Resources/views/benefit/_edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Benefit edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}

    <ul>
        <li>
            <a href="{{ path('benefit_index') }}">Back to the list</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}

src/AppBundle/Resources/views/benefit/_new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Benefit creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="{{ path('benefit_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock %}

src/AppBundle/Resources/views/benefit/index.html.twig
{% extends '@AppBundle/Resources/views/index_layout.html.twig' %}

{% block body_title %}Beneficiarios{% endblock %}

{% block body_search %}
	<form method="GET">
        <div class="form-group">
            <label for="">Nombre</label>
            <input type="text" id="" name="filter[name]" placeholder="Nombre" class="form-control" {% if filter['name'] is defined %} value="{{filter['name']}}" {% endif %}>
        </div>
        <div class="form-group">
            <label for="">DNI</label>
            <input type="text" id="benefit_dni" name="filter[dni]" placeholder="DNI" class="form-control" {% if filter['dni'] is defined %} value="{{filter['dni']}}" {% endif %}>
        </div>
        <div class="form-group">
            <label for="">Tipo</label>
            <select name="filter[type]" placeholder="Tipo" class="form-control">
            	<option value="">Seleccionar</option>
	            {% set i = 0 %}
	            {% for type in types %}
	            	{% set i = i + 1 %}
	            	<option value="{{i}}" {% if filter['type'] is defined and filter['type'] == i %} selected="selected" {% endif %}>{{type}}</option>
	            	
	            {% endfor %}
            </select>
        </div>
        
        <button type="submit" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-search"></i> Buscar</button>
        <a href="{{path('benefit_index')}}" class="btn btn-sm btn-default">Todos</a>
    </form>
{% endblock %}

{% block body_new_button %}
	{% if is_granted(['ROLE_LEVEL2','ROLE_LEVEL3','ROLE_FULL']) %}
	<a href="{{path('benefit_new')}}" class="btn btn-primary btn-sm">Nuevo beneficio</a>
	{% endif %}
{% endblock %}

{% block body_table %}
	<thead>
	    <tr>
	        <th>Nombre</th>
	        <th>DNI/pasaporte</th>
	        <th>Tipo</th>
	        <th>Área/Otro</th>
	        <th>Cargado por</th>
	        <th width="150">Acciones</th>
	    </tr>
	</thead>
	<tbody>
		{% for benefit in pagination %}
		    <tr>
		        <td>{{benefit.fullName}}</td>
		        <td>
		        	{{benefit.dni}}
		        	{% if benefit.passport %}
		        		/ {{benefit.passport}}
		        	{% endif %}
		        </td>
		        <td>{{benefit.typeName}}</td>
		        <td>
		        	{% if benefit.area %}
		        		{{benefit.area.name}}
		        	{% elseif benefit.institutionOther %}
		        		{{benefit.institutionOther}}
		        	{% else %}
		        		No hay datos cargados
		        	{% endif %}
		        </td>
		        <td>
		        	{% if benefit.user %}
		        		{{benefit.user.lastname}}, {{benefit.user.firstName}}
		        	{% else %}
		        		Sin definir
		        	{% endif %}
		        </td>
		        <td>
		        	<a href="{{ path('benefit_show', { 'id': benefit.id }) }}" class="btn btn-xs btn-default" data-toggle="tooltip" title="Ver"><i class="glyphicon glyphicon-eye-open"></i></a>
		        	<a href="{{ path('benefit_pdf', { 'id': benefit.id }) }}" class="btn btn-xs btn-default" data-toggle="tooltip" title="PDF"><i class="glyphicon glyphicon-download"></i></a>
		        	{% if is_granted(['ROLE_LEVEL3','ROLE_FULL']) %}
		            <a href="{{ path('benefit_edit', { 'id': benefit.id }) }}" class="btn btn-xs btn-default" data-toggle="tooltip" title="Editar"><i class="glyphicon glyphicon-edit"></i></a>
		            <a href="{{ path('benefit_delete', { 'id': benefit.id }) }}" class="btn btn-xs btn-default" data-toggle="tooltip" title="Eliminar" onclick="return confirm('¿Está seguro que desea eliminar el registro?')"><i class="glyphicon glyphicon-trash"></i></a>
		        	{% endif %}
		        </td>
		    </tr>
		{% endfor %}
	</tbody>
{% endblock %}
{% block paginator %}
	{{ knp_pagination_render(pagination) }}
{% endblock %}
{% block javascripts %}
	{{parent()}}

	<script src="{{ asset('plugins/jQuery-Mask-Plugin-master/src/jquery.mask.js') }}"></script>

	<script>
	$(document).ready(function(){
		$('#benefit_dni').mask('00.000.000');
	});
	</script>
{% endblock %}

src/AppBundle/Resources/views/benefit/pdf.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
	<style>
		html, body, page {
		    width: 700px;
		    font-size: 14px;
		  }
		table{
			width: 100%
		}
		td{
			border:1px solid;
			vertical-align: top;
			min-height: 25px;
		}
		tr.title td {
			text-align: center;
			font-weight: bold;
			font-size: 16px;
		}
		label{
			font-weight: bold;
		}
	</style>
</head>
<body>
	
		<table>
			<tr class="title"><td colspan="4">Generales</td></tr>
			<tr>
				<td >
					<label >Tipo de beneficio</label>
		            <div>{{benefit.typeName}}</div>
				</td>
				<td >
					<label >DNI</label>
		            <div>{{benefit.dni}}</div>
				</td>
				<td >
					<label >Pasaporte</label>
		            <div>{{benefit.passport}}</div>
				</td>
				<td >
					<label >CUIL</label>
		            <div>{{benefit.cuil}}</div>
				</td>
			</tr>
		</table>
		<table>
			<tr class="title">
				<td colspan="4">Datos personales</td>
			</tr>
			<tr>
				<td  colspan="4">
					<label >Apellidos</label>
		            <div>{{benefit.lastname}}</div>
				</td>
			</tr>
			<tr>
				<td  colspan="4">
					<label >Nombres</label>
		            <div>{{benefit.name}}</div>
				</td>
			</tr>
			<tr>
				<td >
					<label >Fecha de nacimiento</label>
		            <div>{{benefit.birthday|date('d-m-Y')}}</div>
				</td>
				<td >
					<label >Lugar de nacimiento</label>
		        	<div>{{benefit.place}}</div>
				</td>
				<td >
					<label >Nacionalidad</label>
		        	<div>{{benefit.nationality}}</div>
				</td>
			</tr>
			<tr>
				<td >
					<label >Grupo sanguineo</label>
		        	<div>{{benefit.bloodTypeName}}</div>
		        </td>
				<td >
					<label >Estado civil</label>
		        	<div>{{benefit.civilStatusName}}</div>
				</td>
				<td >
					<label >Teléfono</label>
		        	<div>{{benefit.phone}}</div>
				</td>
			</tr>
			<tr>
				<td  colspan="4">
					<label >Email</label>
		        	<div>{{benefit.email}}</div>
				</td>
			</tr>
		</table>
		<table>
			<tr class="title">
				<td colspan="4">Domicilio</td>
			</tr>
		</table>
			
		<table>
			<tr>
				<td >
				<label >Calle</label>
	        	<div>{{benefit.street}}</div>
			</td>
			<td >
				<label >Barrio</label>
	        	<div>{{benefit.neighborhood}}</div>
			</td>	
			</tr>
		</table>
			
		<table>
			<tr>
				<td >
					<label >Ciudad</label>
		        	<div>{{benefit.city}}</div>
				</td>
				<td >
					<label >Departamento</label>
		        	<div>{{benefit.depto}}</div>
				</td>
				<td >
					<label >Código postal</label>
		        	<div>{{benefit.zipCode}}</div>
				</td>
			</tr>
		</table>
			
		<table>
			<tr class="title">
				<td colspan="4">Conocimientos y estudios (completos)</td>
			</tr>
		</table>
		
		<table>
			<tr>
				<td >
					<label >¿Primaria completo?</label>
		        	<div>{% if benefit.isPrimarySchool %}Si{% else %}No{% endif %}</div>
				</td>
				<td >
					<label >¿Ciclo básico?</label>
		        	<div>{% if benefit.isBasicCycle %}Si{% else %}No{% endif %}</div>
				</td>
				<td >
					<label >¿Secundaria completo?</label>
		        	<div>{% if benefit.isHighSchool %}Si{% else %}No{% endif %}</div>
				</td>
			</tr>
			<tr>
				<td >
					<label >¿Terciario completo?</label>
		        	<div>{% if benefit.isTertiarySchool %}Si{% else %}No{% endif %}</div>
				</td>
				<td >
					<label >¿Título universitario?</label>
		        	<div>{% if benefit.isUniversitaryDegree %}Si{% else %}No{% endif %}</div>
				</td>
				<td >
					<label >¿Posgrado?</label>
		        	<div>{% if benefit.isPostgrade %}Si{% else %}No{% endif %}</div>
				</td>
			</tr>
		</table>
			
			
		<table>
			<tr>
				<td >
					<label >Título obtenido</label>
		        	<div>{{benefit.degree}}</div>
				</td>
				<td >
					<label >Estudios en curso</label>
		        	<div>{{benefit.actualStudy}}</div>
				</td>
			</tr>
		</table>
		<table>
			<tr class="title">
				<td colspan="4">Prestación de sercivios</td>
			</tr>
			<tr>
				<td >
					<label >Área / Coordinación / Unidad</label>
		        	<div>{{benefit.area}}</div>
				</td>
				<td >
					<label >Dirección</label>
		        	<div>{{benefit.direction}}</div>
				</td>
				<td >
					<label >Subsecretaría</label>
		        	<div>{{benefit.secretariat}}</div>
				</td>
			</tr>
			<tr>
				<td >
					<label >Ministerio / Secretaria</label>
		        	<div>{{benefit.ministry}}</div>
				</td>
				<td >
					<label >Encargado del área</label>
		        	<div>{{benefit.areaManager}}</div>
				</td>
				<td >
					<label >Institución / otros</label>
		        	<div>{{benefit.institutionOther}}</div>
				</td>
			</tr>
		</table>
		<table>
			<tr class="title">
				<td colspan="2">Archivos</td>
			<tr>
			<tr>
				<td>Legajo personal</td>
				<td>
					{% if files[1] %}
	        			<a href="{{ site ~ files[1]}}" target="_blank">Ver</a>
	        		{% endif %}
				</td>
			</tr>
			<tr>
				<td>DNI</td>
				<td>
					{% if files[2] %}
	        			<a href="{{site ~ files[2]}}" target="_blank">Ver</a>
	        		{% endif %}
				</td>
			</tr>
			<tr>
				<td>Certificación de trabajo</td>
				<td>
					{% if files[3] %}
	        			<a href="{{site ~ files[3]}}" target="_blank">Ver</a>
	        		{% endif %}
				</td>
			</tr>
			<tr>
				<td>Título</td>
				<td>
					{% if files[4] %}
	        			<a href="{{site ~ files[4]}}" target="_blank">Ver</a>
	        		{% endif %}
				</td>
			</tr>
			<tr>
				<td>Constancia de alumno regular</td>
				<td>
					{% if files[5] %}
	        			<a href="{{site ~ files[5]}}" target="_blank">Ver</a>
	        		{% endif %}
				</td>
			</tr>
			
		</table>
	
</body>
</html>